CHART_DPI = 200
CHART_FIGSIZE = (15, 8)
MAP_DPI = 150
MAP_FIGSIZE = (10, 7.5)
FONT_FAMILY = 'Arial'
UNICODE_MINUS = False
DEFAULT_OUTPUT_DIR = "static/pharmacy_report"
DEFAULT_OUTPUT_FILENAME = "report.md"